version: "3.8"
services:
  supernode-1:
    image: flwr/supernode:${FLWR_VERSION:-1.17.0}
    command:
      - --superlink
      - superlink:9092
      - --clientappio-api-address
      - 0.0.0.0:9094
      - --isolation
      - process
      - --node-config
      - "partition-id=0 num-partitions=1"
      - --root-certificates
      - /app/certificates/ca.crt
    volumes:
      - ./certificates/ca.crt:/app/certificates/ca.crt:ro
    networks:
      - flower-network

  clientapp-1:
    build:
      context: ${PROJECT_DIR:-.}
      dockerfile_inline: |
        FROM flwr/clientapp:${FLWR_VERSION:-1.17.0}

        WORKDIR /app
        COPY --chown=app:app pyproject.toml .
        RUN sed -i 's/.*flwr\[simulation\].*//' pyproject.toml \
          && python -m pip install -U --no-cache-dir .

        ENTRYPOINT ["flwr-clientapp"]
    command:
      - --insecure
      - --clientappio-api-address
      - supernode-1:9094
    deploy:
      resources:
        limits:
          cpus: "2"
    stop_signal: SIGINT
    depends_on:
      - supernode-1
    networks:
      - flower-network

networks:
  flower-network:
    external: true